/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef _Included_air_condition_msg
#define _Included_air_condition_msg

typedef struct _Device_Setting{
	uchar wind_status;//风量 
	uchar sleep;//睡眠	
	uchar work:4;//工作模式
	uchar run:4;//运行
	uchar indoor_temperature;//室内温度
	uchar indoor_humidity;//室内湿度
	uchar somatosensory_temperature;//体感温度
	uchar somatosensory_humidity;//体感湿度

	uchar compensation:5;//温度补偿
	uchar rev8:1;	
	uchar showmode:2;//温度显示方式
	uchar timer;//定时 时间
	uchar hour;//小时	
	uchar minute;//分钟	
	uchar poweron_hour;//开机的小时值
	uchar poweron_minute;//开机的分钟值
	uchar poweroff_hour;//关机的小时值
	uchar poweroff_minute;//关机的分钟值	
	uchar drying:4;//除湿
	uchar air_door:4;//风门
	
	uchar up_down:2;//上下风
	uchar left_right:2;//左右风
	uchar nature:2;//自然风
	uchar heat:2;//加热风

	uchar low_power:2;//节能
	uchar low_electricity:2;//节电
	uchar efficient:2;//高效
	uchar dual_frequency:2;//双频

	uchar dew:2;//清新
	uchar swap:2;//换风
	uchar indoor_clear:2;//室内清洁
	uchar outdoor_clear:2;//室外清洁
	
	uchar smart_eye:2;//智慧眼
	uchar mute:2;//静音
	uchar voice:2;//语音
	uchar smoke:2;//除烟
	
	uchar back_led:2;//背景灯
	uchar display_led:2;//显示屏
	uchar indicate_led:2;//指示灯
	uchar indoor_led:2;//室内室外切换灯

	uchar filter_reset:2;//过滤网复位
	uchar left_wind:2;//左风
	uchar right_wind:2;//右风
	uchar rev22:2;

	uchar auto_check:2;//自检
	uchar time_lapse:2;//缩时
	uchar rev23:4;

	uchar rev24;
	uchar rev25;
	uchar rev26;
	uchar rev27;
	uchar rev28;
	uchar rev29;
	uchar rev30;	
}Device_Setting;

typedef struct _Message_101_0{
	MessageHead                 Head;
	Device_Setting				Setting;
}Message_101_0;

typedef struct _Device_Time{
	uchar second;
	uchar minute;	
	uchar hour;
	uchar week;
	uchar day;
	uchar month;
	uchar year;
}Device_Time;

typedef struct _Message_101_32{
	MessageHead                 Head;
	Device_Time					Time;
}Message_101_32;

typedef struct _Device_Status{
	uchar wind_status;//风量
	uchar sleep_status;//睡眠
	
	uchar mode_status:4;//模式  
	uchar run_status:2;//运行
	uchar direction_status:2;//风向
	// 4
	uchar indoor_temperature_setting;//室内温度
	uchar indoor_temperature_status;//室内温度
	uchar indoor_pipe_temperature;//室内管温值
	// 7
	uchar indoor_humidity_setting;//室内湿度
	uchar indoor_humidity_status;//室内湿度
	
	uchar somatosensory_temperature;//体感温度
	// 10
	uchar somatosensory_compensation:5;//体感补偿
	uchar somatosensory_compensation_ctrl:3;//体感补偿控制
    // 11
	uchar temperature_compensation:5;//温度补偿
	uchar temperature_Fahrenheit:3;//华氏显示
	
	// 12
	uchar timer;//定时

	// 13
	uchar hour;
	// 14
	uchar minute;
	// 15
	uchar poweron_hour;
	// 16
	uchar poweron_minute;
	// 17
	uchar poweroff_hour;
	// 18
	uchar poweroff_minute;
	// 19
	uchar drying:4;
	uchar wind_door:4;
	// 20
	uchar up_down:1;//上下风
	uchar left_right:1;//左右风
	uchar nature:1;//自然风
	uchar heat:1;//加热风
	uchar low_power:1;//节能
	uchar low_electricity:1;//节电
	uchar efficient:1;//高效
	uchar dual_frequency:1;//双频
	// 21
	uchar dew:1;//清新
	uchar swap:1;//换风
	uchar indoor_clear:1;//室内清洁
	uchar outdoor_clear:1;//室外清洁
	uchar smart_eye:1;//智慧眼
	uchar mute:1;//静音
	uchar voice:1;//语音
	uchar smoke:1;//除烟
	// 22
	uchar back_led:1;//背景灯
	uchar display_led:1;//显示屏
	uchar indicate_led:1;//指示灯
	uchar indoor_led:1;//室内室外切换灯

	uchar filter_reset:1;//过滤网复位
	uchar left_wind:1;//左风
	uchar right_wind:1;//右风
	uchar indoor_electric:1;//室内电量板
	//23
	uchar auto_check:1;//自检
	uchar time_lapse:1;//缩时
	uchar rev23:4;
	uchar sample:1;//样品
	uchar indoor_eeprom:1;//eeprom
	//24
	uchar indoor_temperature_sensor:1;
	uchar indoor_temperature_pipe_sensor:1;
	uchar indoor_humidity_sensor:1;
	uchar indoor_water_pump:1;
	uchar indoor_machine_run:1;
	uchar indoor_bars:1;
	uchar indoor_zero_voltage:1;
	uchar indoor_outdoor_communication:1;

	//25
	uchar display_communication:1;
	uchar keypad_communication:1;
	uchar wifi_communication:1;
	uchar electric_communication:1;
	uchar eeprom_communication:1;
	uchar rev25:3;
	//26
	uchar compressor_frequency;
	//27
	uchar compressor_frequency_setting;
	//28
	uchar compressor_frequency_send;
	//29
	uchar outdoor_temperature;
	//30
	uchar outdoor_condenser_temperature;
	//31
	uchar compressor_exhaust_temperature;
	//32
	uchar target_exhaust_temperature;
	//33
	uchar expand_threshold;
	//34
	uchar UAB_HIGH;
	//35
	uchar UAB_LOW;
	//36
	uchar UBC_HIGH;
	//37
	uchar UBC_LOW;
	//38
	uchar UCA_HIGH;
	//39
	uchar UCA_LOW;
	//40
	uchar IAB;
	//41
	uchar IBC;
	//42
	uchar ICA;
	//43
	uchar generatrix_voltage_high;
	//44
	uchar generatrix_voltage_low;
	//45
	uchar IUV;
	//46
	uchar rev46:3;
	uchar four_way:1;
	uchar outdoor_machine:1;
	uchar wind_machine:3;
	//47
	uchar rev47;
	//48
	uchar rev48;
	//49
	uchar rev49;
	//50
	uchar rev50;
	//51
	uchar rev51;
	//52
	uchar rev52;
	//53
	uchar rev53;
	//54
	uchar rev54;
	//55
	uchar rev55;
	//56
	uchar rev56;
}Device_Status;

typedef struct _Message_102_0{
	MessageHead                 Head;
	Device_Status				Status;
}Message_102_0;

typedef struct _Message_102_32{
	MessageHead                 Head;
	Device_Time					Time;
}Message_102_32;

typedef struct _Device_Power{
	uchar ONE_KWH_I;
	uchar ONE_KWH_F;	
	uchar ONE_KWH_D;
	uchar KWH_DAY;
	uchar KWH_WEEK_H;
	uchar KWH_WEEK_L;
	uchar KWH_MONTH_H;
	uchar KWH_MONTH_L;
	uchar KWH_QUARTER_H;
	uchar KWH_QUARTER_L;	
	uchar KWH_HALFYEAR_H;
	uchar KWH_HALFYEAR_L;
	uchar KWH_YEAR_H;
	uchar KWH_YEAR_L;
	uchar KWH_H;
	uchar KWH_SH;
	uchar KWH_SL;
	uchar KWH_L;
}Device_Power;

typedef struct _Message_102_48{
	MessageHead                 Head;
	Device_Power				Power;
}Message_102_48;

#endif
