/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef _Included_Command
#define _Included_Command
/*
构造要发送的报文,由proc_cmd和send_multi_cmd 函数调用
参数:
pxm:socket 数据指针
argc:参数个数
argv:参数数组
返回:
出错代码
*/
uchar ProcCmd(XM_PROTOCOL *pxm,uchar argc,char **argv);
#endif
