/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef _Included_Message
#define _Included_Message
#pragma pack(1)
typedef struct _MessageHead{
	uchar                       MessageType;
	uchar                       MessageSubType;
	uchar                       Result;
	uchar 						frame;
	uchar 						sub_frame;
}MessageHead;
#pragma pack( )

//设备地址
#define XM_NEW 				0
#define XM_AIR_CONDITION	1
#define XM_REFRIGERATOR		2
#define XM_FREEZER			3
#define XM_WATER_HEATER		4
/*
生成命令字和内容
参数:
pxm:socket 数据指针
pbuf:保存命令和内容
Type:命令字
SubType:子命令
pData:内容
DataLen:内容长度
返回:
报文长度
*/
uchar New_Msg_Head(XM_PROTOCOL *pxm,uchar * pbuf,uchar Type,uchar SubType,uchar *pData,int DataLen);
/*
判断命令执行是否成功
参数:
pxm:socket 数据指针
pMsg:命令和内容
len:命令和内容长度
返回:
出错代码
*/
uchar Proc_Result(XM_PROTOCOL *pxm,MessageHead * pMsg,uchar len);
#endif
